const customersList = [
  {
    customerId: 1,
    fullName: "Dorian Mckee",
    phoneNumber: "1-874-275-7055",
    email: "mattis@hotmail.ca",
    address: "5913 Id Avenue",
    userName: "Yen Hooper",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 2,
    fullName: "Britanney Hammond",
    phoneNumber: "1-586-705-7373",
    email: "nunc.quisque.ornare@google.org",
    address: "Ap #889-1063 Molestie Rd.",
    userName: "Rebekah Madden",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 3,
    fullName: "Stephanie Farmer",
    phoneNumber: "1-224-715-8816",
    email: "a.arcu.sed@hotmail.edu",
    address: "Ap #283-4013 Ullamcorper, St.",
    userName: "Eric Moses",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 4,
    fullName: "Madeson Hodges",
    phoneNumber: "1-650-719-5169",
    email: "phasellus.ornare@google.org",
    address: "Ap #909-735 Eget Street",
    userName: "Gage Boyer",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 5,
    fullName: "Frances Schultz",
    phoneNumber: "1-142-543-8698",
    email: "feugiat.nec@hotmail.org",
    address: "Ap #129-856 Dictum. Rd.",
    userName: "Dora Walls",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 6,
    fullName: "Chastity Coleman",
    phoneNumber: "(326) 742-8065",
    email: "donec.tincidunt@hotmail.com",
    address: "Ap #876-5174 Diam. Avenue",
    userName: "Rose Delaney",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 7,
    fullName: "Calvin Goodwin",
    phoneNumber: "1-353-925-5831",
    email: "nec.mauris@aol.com",
    address: "296-1154 Elit, St.",
    userName: "Lee Lewis",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 8,
    fullName: "Hayden Rowe",
    phoneNumber: "(928) 272-7324",
    email: "donec.felis@google.edu",
    address: "Ap #216-3740 Tellus Rd.",
    userName: "Destiny Keller",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 9,
    fullName: "Alice Farrell",
    phoneNumber: "(392) 892-8612",
    email: "sit.amet@yahoo.org",
    address: "856-8154 Fusce Rd.",
    userName: "Valentine Duncan",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 10,
    fullName: "Giacomo Olsen",
    phoneNumber: "1-461-868-7111",
    email: "rutrum@hotmail.edu",
    address: "813-5537 Aliquam Rd.",
    userName: "Guy Rush",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 11,
    fullName: "Emery Garner",
    phoneNumber: "1-831-677-3573",
    email: "amet.consectetuer.adipiscing@outlook.edu",
    address: "Ap #503-7242 Sed Rd.",
    userName: "Davis Ramsey",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 12,
    fullName: "Wyatt Frazier",
    phoneNumber: "1-989-168-2452",
    email: "amet.luctus.vulputate@hotmail.net",
    address: "6837 A Road",
    userName: "Samantha Park",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 13,
    fullName: "Chantale Jimenez",
    phoneNumber: "(272) 459-0263",
    email: "pede@aol.org",
    address: "163-5774 Sed Av.",
    userName: "Blake Durham",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 14,
    fullName: "McKenzie Good",
    phoneNumber: "(218) 243-1187",
    email: "quisque.fringilla.euismod@google.couk",
    address: "Ap #755-3293 Libero. Ave",
    userName: "Alea Hernandez",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 15,
    fullName: "Katelyn Griffin",
    phoneNumber: "1-312-221-1768",
    email: "neque@yahoo.org",
    address: "8898 Suspendisse Road",
    userName: "Tucker Sanchez",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 16,
    fullName: "Vance Bentley",
    phoneNumber: "1-942-758-7559",
    email: "aliquet@icloud.edu",
    address: "Ap #766-397 Libero Rd.",
    userName: "Jaquelyn Hebert",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 17,
    fullName: "Patricia Palmer",
    phoneNumber: "1-641-561-0432",
    email: "integer@icloud.com",
    address: "7262 Sociis Rd.",
    userName: "Channing King",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 18,
    fullName: "Angela Navarro",
    phoneNumber: "1-861-857-4694",
    email: "adipiscing.elit@outlook.org",
    address: "Ap #740-8688 Vulputate, St.",
    userName: "Dexter Chaney",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 19,
    fullName: "Kuame Dorsey",
    phoneNumber: "(617) 302-8270",
    email: "ac.mattis@outlook.com",
    address: "Ap #713-4586 Quisque Rd.",
    userName: "Candace Alvarez",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 20,
    fullName: "Callum Clemons",
    phoneNumber: "(908) 603-5483",
    email: "posuere.cubilia.curae@icloud.couk",
    address: "843-7170 Nisi. St.",
    userName: "Colin Roach",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 21,
    fullName: "Robin Estrada",
    phoneNumber: "(848) 217-2657",
    email: "quisque.porttitor.eros@yahoo.edu",
    address: "4727 Ad Av.",
    userName: "Blossom Stark",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 22,
    fullName: "Orla Sawyer",
    phoneNumber: "(288) 539-0754",
    email: "lectus.pede@hotmail.net",
    address: "Ap #226-9141 Mauris. St.",
    userName: "Camille Thomas",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 23,
    fullName: "Baker Lyons",
    phoneNumber: "(193) 819-1675",
    email: "mauris.rhoncus@hotmail.couk",
    address: "Ap #338-9986 Dignissim Rd.",
    userName: "Chaim Dennis",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 24,
    fullName: "Fuller Hurst",
    phoneNumber: "1-743-428-4360",
    email: "diam.luctus@outlook.ca",
    address: "473 Sed Ave",
    userName: "Paloma Pace",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 25,
    fullName: "Noelani Baker",
    phoneNumber: "1-791-578-8411",
    email: "risus.odio@protonmail.com",
    address: "Ap #681-6672 Ultricies Av.",
    userName: "Kato Spears",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 26,
    fullName: "Jeremy Nash",
    phoneNumber: "1-760-218-7327",
    email: "nam.porttitor.scelerisque@hotmail.couk",
    address: "5445 Eu Road",
    userName: "Maxine Mathis",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 27,
    fullName: "Ulric Dillard",
    phoneNumber: "(758) 571-3242",
    email: "convallis.ligula.donec@yahoo.net",
    address: "P.O. Box 486, 4175 Mattis Rd.",
    userName: "Holmes Patel",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 28,
    fullName: "Florence Pitts",
    phoneNumber: "1-513-288-8458",
    email: "in@icloud.org",
    address: "217-364 Ut St.",
    userName: "Lois Larsen",
    image: "/images/female.jpg",
    gender: "female",
  },
  {
    customerId: 29,
    fullName: "Dieter Emerson",
    phoneNumber: "1-476-733-1745",
    email: "ornare.in@hotmail.ca",
    address: "2523 Nec, Rd.",
    userName: "Wilma Robbins",
    image: "/images/male.jpg",
    gender: "male",
  },
  {
    customerId: 30,
    fullName: "Randall Moses",
    phoneNumber: "1-412-735-8316",
    email: "egestas.lacinia.sed@google.net",
    address: "P.O. Box 417, 9136 Cursus St.",
    userName: "Yen Monroe",
    image: "/images/male.jpg",
    gender: "male",
  },
];

const headers = {
  "Access-Control-Allow-Origin": "*",
};

const recordsPerPage = 7;

const PORT = process.env.PORT || 9000;

module.exports = { customersList, headers, recordsPerPage, PORT };
